<Project>
  <PropertyGroup>
    <IsLinux>$([MSBuild]::IsOSPlatform('Linux'))</IsLinux>
    <IsOSX>$([MSBuild]::IsOSPlatform('OSX'))</IsOSX>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsOSX)' == 'True'">
    <SteamLibraryPath Condition="'$(SteamLibraryPath)' == ''">$(HOME)/Library/Application Support/Steam/steamapps</SteamLibraryPath>
    <Sts2Path Condition="'$(Sts2Path)' == ''">$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
    <ModsPath Condition="'$(ModsPath)' == ''">$(Sts2Path)/SlayTheSpire2.app/Contents/MacOS/mods/</ModsPath>
    <Sts2DataDirArm>$(Sts2Path)/SlayTheSpire2.app/Contents/Resources/data_sts2_macos_arm64</Sts2DataDirArm>
    <Sts2DataDir Condition="'$(Sts2DataDir)' == '' and Exists('$(Sts2DataDirArm)')">$(Sts2DataDirArm)</Sts2DataDir>
    <Sts2DataDir Condition="'$(Sts2DataDir)' == ''">$(Sts2Path)/SlayTheSpire2.app/Contents/Resources/data_sts2_macos_x86_64</Sts2DataDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsLinux)' == 'True'">
    <SteamLibraryPath Condition="'$(SteamLibraryPath)' == ''">$(HOME)/.local/share/Steam/steamapps</SteamLibraryPath>
    <Sts2Path Condition="'$(Sts2Path)' == ''">$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
    <ModsPath Condition="'$(ModsPath)' == ''">$(Sts2Path)/mods/</ModsPath>
    <Sts2DataDir Condition="'$(Sts2DataDir)' == ''">$(Sts2Path)/data_sts2_linuxbsd_x86_64</Sts2DataDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsOSX)' != 'True' and '$(IsLinux)' != 'True'">
    <SteamLibraryPath Condition="'$(SteamLibraryPath)' == ''">C:/Program Files (x86)/Steam/steamapps</SteamLibraryPath>
    <Sts2Path Condition="'$(Sts2Path)' == ''">$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
    <ModsPath Condition="'$(ModsPath)' == ''">$(Sts2Path)/mods/</ModsPath>
    <Sts2DataDir Condition="'$(Sts2DataDir)' == ''">$(Sts2Path)/data_sts2_windows_x86_64</Sts2DataDir>
  </PropertyGroup>
</Project>
